## Create arrays

In [1]:
import numpy as np

In [4]:
# Create two 1D arrays
x = np.arange(10)
y = x**2
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


## Save arrays with Numpy's `savez`

In [5]:
np.savez('x_y-squared.npz', x_axis=x, y_axis=y)

## Load compressed arrays

In [6]:
# Delete the arrays from memory
del x, y
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>


In [7]:
# Load compressed arrays
load_xy = np.load('x_y-squared.npz')
print(load_xy.files)

['x_axis', 'y_axis']


In [8]:
%whos

Variable   Type       Data/Info
-------------------------------
load_xy    NpzFile    NpzFile 'x_y-squared.npz'<...>with keys: x_axis, y_axis
np         module     <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>


In [9]:
# Retrieve arrays
x = load_xy['x_axis']
y = load_xy['y_axis']   
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]
