## Save arrays with Numpy's `savez`

In [1]:
import numpy as np

In [4]:
# Create two 1D arrays
x = np.arange(10)
y = x**2
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


In [5]:
np.savez('x_y-squared.npz', x_axis=x, y_axis=y)

In [6]:
# Delete the arrays from memory
del x, y
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>


In [7]:
# Load compressed arrays
load_xy = np.load('x_y-squared.npz')
print(load_xy.files)

['x_axis', 'y_axis']


In [8]:
%whos

Variable   Type       Data/Info
-------------------------------
load_xy    NpzFile    NpzFile 'x_y-squared.npz'<...>with keys: x_axis, y_axis
np         module     <module 'numpy' from 'c:\<...>ges\\numpy\\__init__.py'>


In [9]:
# Retrieve arrays
x = load_xy['x_axis']
y = load_xy['y_axis']   
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


## Save arrays to human-readable csv

In [10]:
# Create 2D array from two 1D arrays
array_out = np.block([x[:, np.newaxis], y[:, np.newaxis]])
print("the output array has shape ", array_out.shape, " with values:")
print(array_out)

the output array has shape  (10, 2)  with values:
[[ 0  0]
 [ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]
 [ 5 25]
 [ 6 36]
 [ 7 49]
 [ 8 64]
 [ 9 81]]


In [12]:
# Save arrays to human-readable csv
np.savetxt('x_y-squared.csv', X=array_out, header='x, y', delimiter=',')
!head x_y-squared.csv

# x, y
0.000000000000000000e+00,0.000000000000000000e+00
1.000000000000000000e+00,1.000000000000000000e+00
2.000000000000000000e+00,4.000000000000000000e+00
3.000000000000000000e+00,9.000000000000000000e+00
4.000000000000000000e+00,1.600000000000000000e+01
5.000000000000000000e+00,2.500000000000000000e+01
6.000000000000000000e+00,3.600000000000000000e+01
7.000000000000000000e+00,4.900000000000000000e+01
8.000000000000000000e+00,6.400000000000000000e+01


In [13]:
# Delete the arrays from memory
del x, y
# Load arrays from human-readable csv
load_xy = np.loadtxt('x_y-squared.csv', delimiter=',')
load_xy.shape

(10, 2)

In [15]:
# Retrieve arrays
x = load_xy[:, 0]
y = load_xy[:, 1]   
print(x)
print(y)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
